spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    username: postgres
    password: vitalspring10

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

jwt:
  secret: "MWRkZDU5YmQ0YTU4Y2Y4YzQ0OTQxMWY2YjA5ZjQxOWIxODg4NmRmNDU0M2VkODZiM2Y5NzQzOTVhMjQ0ZjE4YQ=="
  expiration: 900000

logging:
  level:
    org.hibernate.SQL: DEBUG